server:
  port: 8082
  servlet:
    context-path: /sekolah
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_sekolah
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  liquibase:
    change-log: classpath:database/changelog/changelog.xml
